<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cetak Daftar_cari</name>
   <tag></tag>
   <elementGuidId>f928fa9c-1ecc-4a9f-bad4-bb3b97f71406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cari&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cari']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f42daf2-237a-4e62-9b79-6fbdd0a0ba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c6436637-400f-4677-9059-ec22565520ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cari</value>
      <webElementGuid>07af2841-db89-4859-9a26-c8960c70b51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>177ad82b-5999-460e-981f-1843dd06ced7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-md btn-primary</value>
      <webElementGuid>6bee4d51-5b2e-460d-ac37-5bb5ad94d0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>margin</name>
      <type>Main</type>
      <value>6px;</value>
      <webElementGuid>e126ee40-08c6-45cf-ba03-75a00125cb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50px;</value>
      <webElementGuid>f8f14b02-dbd7-4d73-8f55-09d18759ae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-11&quot;]/div[1]/form[1]/input[@class=&quot;btn-md btn-primary&quot;]</value>
      <webElementGuid>da481cc1-f82b-43d2-9bab-0ce77d1d4519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cari']</value>
      <webElementGuid>a468e278-3b21-4ce8-8f08-f53e64d379e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div/div/form/input[2]</value>
      <webElementGuid>0a8e6d71-0fbe-429e-8ed0-252184007aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>49e92392-7734-43ce-9946-483ebd9b6263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'cari']</value>
      <webElementGuid>21cc80ce-5bec-4a19-938f-9e3272095cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
