<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Istri  Suami_nama_istri (1) (1)</name>
   <tag></tag>
   <elementGuidId>c12ec87c-695e-4608-be22-3f50b4a6d61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_istri</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_istri']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6da1b8b-b5ca-4eee-ad41-2652dfe2e58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bfcbcedd-39a3-4a06-86b9-566f08121146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>acefbb6e-a09a-41b5-b5a3-0637df440d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>1b6cade5-861a-4d0f-9553-93c6fc7ed569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Istri</value>
      <webElementGuid>5d14a492-8933-4ede-9989-e28cf8fe0fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>070444b9-a698-4d33-a813-d9c88b2f942f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b41cfc1d-049a-485e-8496-9904986a011d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_istri&quot;)</value>
      <webElementGuid>78aa4908-b46f-416a-a455-0ff73e492602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_istri']</value>
      <webElementGuid>16adb467-d762-46f8-aa75-4661d143a7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[4]/input</value>
      <webElementGuid>0f7554a8-53fd-4a6d-bc87-cd6483df88e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>950b1558-f4d9-4aa9-8f68-da1e97e40064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_istri' and @id = 'nama_istri' and @placeholder = 'Nama Istri' and @type = 'text']</value>
      <webElementGuid>d1db2957-f9f9-4f67-8d4d-386573c46078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
