<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Id User_id_user (3)</name>
   <tag></tag>
   <elementGuidId>8fb2489d-a74e-4b8c-8487-2d4b5b2a7f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90902d92-60e1-432c-81ed-ad0cd91702e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2e67ed46-408d-46da-bd47-3a8eef174edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>7b54e7e8-9330-4703-8187-ed21d51dd828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>83409347-ad51-4766-9113-a0378b228183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a68434a8-fe39-497c-9325-47fd7df63199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Id User</value>
      <webElementGuid>86f38d45-1e4a-4006-b130-701425b6e87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>74c70ad4-c558-4a8a-a428-e03a3cbe6944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_user&quot;)</value>
      <webElementGuid>b6dac861-799c-4c92-b053-6d1d2fa3e5f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_user']</value>
      <webElementGuid>c70657ef-e7a9-4b77-b322-fc1abd15d40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div/input</value>
      <webElementGuid>52988558-0c3d-49ea-b6d7-c0de77585caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>848177e1-6268-4fc5-8e1a-8fdb5768ab94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'id_user' and @id = 'id_user' and @type = 'text' and @placeholder = 'Id User']</value>
      <webElementGuid>cffe525f-d22f-4606-a894-ef3eb7433739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
