<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Istri  Suami_nama_istri</name>
   <tag></tag>
   <elementGuidId>9964e355-0398-4672-9d07-6f92bbcc1e59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_istri</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_istri']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aba5999-3a72-4879-9cb1-466c233d8d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf450dfc-1a90-4cd4-a5ba-861c2dab203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>1243e34a-90d3-46ae-95e6-b26c92f4eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>a855ec09-f67e-43ff-93e6-b9657e9c38d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Istri</value>
      <webElementGuid>efe3de7f-b782-4cb8-9166-018cfee10953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>500b030b-7d0f-409a-b726-907ae9a21313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e91fc364-2105-4a10-8ca9-ab17f5455f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_istri&quot;)</value>
      <webElementGuid>75ec30ce-d4c5-4b3d-99d5-4a0ea80943b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_istri']</value>
      <webElementGuid>783ec872-9cc9-436c-bc81-2cdecb9de5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[4]/input</value>
      <webElementGuid>1c869ac2-9a7a-4260-8727-08572321c9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5ef5774d-a1a4-4e86-b3a0-e3b8f336956c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_istri' and @id = 'nama_istri' and @placeholder = 'Nama Istri' and @type = 'text']</value>
      <webElementGuid>138877e3-d6de-47cc-9d34-0663cc7dea72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
