<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Tenaga Kerja Musiman_jml_tng_k_49b205</name>
   <tag></tag>
   <elementGuidId>69c45eb9-23af-40d9-a703-ab533863859f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jml_tng_kerja_musiman&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jml_tng_kerja_musiman']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e31d10e-b3db-4ea1-901d-8c8ce8acba92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f6835293-ee75-4162-9417-7e31ec3ae19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jml_tng_kerja_musiman</value>
      <webElementGuid>f887ea1e-ca09-4656-8e40-3d88ab51368c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>391bd635-9f27-4f05-881d-1208145cc2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>dd8942b1-feb9-456b-807d-6b1ae7d3053c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jml_tng_kerja_musiman']</value>
      <webElementGuid>db47e456-9a70-4b33-832d-e3e1ae15d78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[6]/input</value>
      <webElementGuid>0cc4e04f-6378-428b-b212-d3016443018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>d22f87a8-0eca-4e19-824b-a164fba8b817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jml_tng_kerja_musiman' and @type = 'text']</value>
      <webElementGuid>b98d11ee-f614-4717-b7ca-d5cc29b960af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
