<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Tanggungan_jumlah_tanggungan (1) (1)</name>
   <tag></tag>
   <elementGuidId>312ba404-1530-43ae-a417-e2cf9ce9197d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jumlah_tanggungan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jumlah_tanggungan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adc7d7c0-9211-40b3-ad19-6f3c8f5ef7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d68b3f18-b465-4917-909d-e4a93f5967b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_tanggungan</value>
      <webElementGuid>d060530c-0c9a-4dab-b6a2-29fb4d36e67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd4f0471-0f8e-4131-bacd-efdfbcf07fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>00391644-a912-46c5-a252-d829e42a9645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jumlah_tanggungan']</value>
      <webElementGuid>02ee97a2-109a-4e78-9d79-a6a7bbf01280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[5]/input</value>
      <webElementGuid>9ef9a6f6-72ff-4dd5-8cb8-70f70d119ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[5]/input</value>
      <webElementGuid>7756017f-cbaa-47d7-8efd-4a8f84137b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jumlah_tanggungan' and @type = 'text']</value>
      <webElementGuid>a7ed3f43-1bfe-4833-a2d1-81877f286eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
