<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Id User_id_user (3) (1) (1)</name>
   <tag></tag>
   <elementGuidId>2ea1ed71-279b-4450-9ee4-6a939c0572af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94ee2fd8-fcf8-4145-b62c-a9bb2ff0506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1923fde1-0a64-4f04-b946-d70812e5da8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>810f4238-0b77-4b3e-bcfb-1ef0478a39f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>88dcba3e-8073-44b5-a957-16b554a30b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0c9872a-2850-4242-81ec-4d2c9adb026f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Id User</value>
      <webElementGuid>981236a8-f9bf-4afb-8a13-2a985fdbe7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>52bea3c1-8289-40d1-8383-948904e93057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_user&quot;)</value>
      <webElementGuid>5217351c-b33b-48b9-84f5-fc869ecb6273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_user']</value>
      <webElementGuid>f4b58ae2-a027-4d07-b4f5-f41084499645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div/input</value>
      <webElementGuid>7e59d322-441d-4e67-9a83-7b1a85cec86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d1d96452-8a39-4efe-8a03-ed90498c26a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'id_user' and @id = 'id_user' and @type = 'text' and @placeholder = 'Id User']</value>
      <webElementGuid>db477f18-5a11-46a1-b5c7-dde1733a25f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
