<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Desa  KelurahanGEDONGKIWOMANTRIJERON_b15df8 (1)</name>
   <tag></tag>
   <elementGuidId>7e8a16f2-2ae4-4545-9e15-dbc93e436802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Desa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Desa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98e66a6d-b588-4531-aca7-e069c8c06d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f05e7ca0-d295-4863-bb55-0492ecc3f9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Desa</value>
      <webElementGuid>66a0573f-9860-4822-b3c8-6f8d6db52433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Desa_Kelurahan</value>
      <webElementGuid>a712d52e-aa40-4197-8ba1-b07dc4ee699c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN</value>
      <webElementGuid>eb223dc9-ea8f-46dd-9e6b-71f03c1e3e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desa&quot;)</value>
      <webElementGuid>ae7e26ed-8a11-42a9-85aa-2cd6d2d5d6d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Desa']</value>
      <webElementGuid>e288bde3-7f61-487f-b806-1348499b73c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[3]/select</value>
      <webElementGuid>94edb846-3be6-46b7-b8f7-7492ce0c00ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/following::select[1]</value>
      <webElementGuid>730c85bc-2b48-48a1-abc3-28d50913543c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[2]</value>
      <webElementGuid>62b5cf78-ab79-4872-96c2-6ffadd025cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[1]</value>
      <webElementGuid>287b87e7-c066-4c1b-acdf-52974bc8d04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/preceding::select[1]</value>
      <webElementGuid>995e039c-6c24-4fb9-ac7b-7b1d8a525530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/select</value>
      <webElementGuid>952cbced-3e48-4d9b-b42a-b2557eeeba30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Desa' and @name = 'Desa_Kelurahan' and (text() = 'Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN' or . = 'Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN')]</value>
      <webElementGuid>c756825d-98a1-442e-92c3-b59ba091dae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
