<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanMANTRIJERONKRATONMERGANGSAN_999684</name>
   <tag></tag>
   <elementGuidId>19030e86-423f-4ce3-86bd-73af65c7b51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bc44ffa-edf9-438d-b70a-ac85806a3670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c4ffc63-5949-4a64-bad4-afa3f8949f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>06cb131c-39b8-4943-9dc3-e4009f388e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>bba9fb00-b9c9-4ac2-b909-7eba067b6f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO</value>
      <webElementGuid>60b612de-4fe9-432e-9344-66620d1b0991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>9738b77d-b671-489a-be13-281ccc1541ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>993c1330-09f0-4ab0-a281-07cf5f3331de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>fb28d117-a5d6-4aa9-b250-0c18d210a57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>84996382-8938-49b5-b376-2a319f230fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>5413fd6f-6908-4b1e-ab71-06579deccc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>c1fe9f2a-990b-4a3a-afb1-69856eada8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>6a4e847b-a434-410f-8dc7-4d1f295ba719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>ec704f81-5687-4265-b006-1813513f1cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO' or . = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO')]</value>
      <webElementGuid>68fd8959-59b2-4872-98d7-793c3a9aeee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
