<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanMANTRIJERONKRATONMERGANGSAN_999684 (1) (1)</name>
   <tag></tag>
   <elementGuidId>40ba3203-67d6-4f86-b0b6-f681dc566995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>38c4e034-46d1-45b0-b34b-892323d74545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87bc0084-6e9e-43b1-a874-781fa8f04224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>c24758d7-3921-41a7-9e99-eb1511f3d375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>8b833b65-a0dd-4a4c-9022-ff9d38c04aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO</value>
      <webElementGuid>3bf05d29-8e5a-4da2-8fc3-49783530dc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>c7412c2b-b4c3-4e12-ba17-8e15dd40f215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>a74746fd-2126-4fac-b442-79c085df7ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>b662323e-ac46-4820-b180-9671425acba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>143c7577-5e71-4146-8f5e-ca6bae855d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>56e2d052-4f96-43ee-b2ec-059284865758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>3202798b-cff7-42f8-be8b-6b214d6d7182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>db64298f-1ed9-4c3f-ab3d-131def1c0acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>2df033ee-674a-43a0-b3ca-767de3b202c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO' or . = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO')]</value>
      <webElementGuid>6b6bd0ff-64cc-4452-91b9-142cb51e93e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
