<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanMANTRIJERONKRATONMERGANGSAN_999684 (1)</name>
   <tag></tag>
   <elementGuidId>88e8d21d-6ede-4906-8d91-2c0f62bd1de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb2b009d-600c-4ea2-946f-68145183a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be2922a7-a043-4be5-92ca-46ce066c1b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>1523e888-117f-49ff-b208-5b16437cf156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>f94d1529-0f07-4776-8702-cf38abfcccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO</value>
      <webElementGuid>a7dcbe24-eb0c-4bad-b8a3-a1a795984462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>5cf39530-4bf1-496b-8878-ff2c57ae980b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>2b461006-8cb1-4493-9781-af3af24a60b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>8a6b2f6d-5f5f-4b67-8abe-f51f5bb272f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>60a82cc2-f853-4357-97fd-d671dbc6555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>d8b1ff03-b8a5-4217-b39e-f3984d7fad53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>6680af19-ad0a-47e0-8a40-27ab3ff4ab78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>259b89b4-fdc8-49bc-a199-c37704ec58d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>194131ab-48b5-41d6-bdc5-bdfb8f8f8900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO' or . = 'KecamatanMANTRIJERONKRATONMERGANGSANUMBULHARJOKOTAGEDEGONDOKUSUMANDANUREJANPAKUALAMANGONDOMANANNGAMPILANWIROBRAJANGEDONG TENGENJETISTEGALREJO')]</value>
      <webElementGuid>1852f9a4-a097-40d6-9a61-990554e24b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
