<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Islam                               _f363b0</name>
   <tag></tag>
   <elementGuidId>53abd7d0-d86f-4c5e-925e-6ac0f3f63b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;agama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='agama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1010698-63be-4bc2-a3a4-98b47b5dc387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5694a2e-0e0f-4f01-8443-b96e6ebb78b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agama</value>
      <webElementGuid>24fbf0b0-3fe1-4db5-a30b-fff6354e31c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                </value>
      <webElementGuid>8a91fc0d-4e46-4e0f-b0ad-880a32e04051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5d93a399-ed6f-463a-85d9-4a4bf088c97f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='agama']</value>
      <webElementGuid>79f14e6c-fb9a-43da-b2e3-6841cd7ebfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[8]/select</value>
      <webElementGuid>adfff447-6edb-4cd2-8b56-83e7cbaeb757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agama *'])[1]/following::select[1]</value>
      <webElementGuid>2a0e726a-e304-484b-9227-8c3e205a92de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email *'])[1]/following::select[1]</value>
      <webElementGuid>ea3d766d-2913-4a8f-b6e8-ca1cf7e475eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Keahlian *'])[1]/preceding::select[1]</value>
      <webElementGuid>77daf3bb-98ed-49a7-b7a3-9ba7b6af4d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Petani *'])[1]/preceding::select[1]</value>
      <webElementGuid>028dba50-ff69-4368-8778-48aa50dda87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>8b9d8e7a-51cf-4bf6-9a2d-d5b5e9d3f529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agama' and (text() = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ' or . = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ')]</value>
      <webElementGuid>bd5fa82b-0b5f-4875-8502-3b9533711b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
