<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BANTULKABUPATEN G_999db8 (1)</name>
   <tag></tag>
   <elementGuidId>1705d69a-e010-4e50-b2a2-0118360dfb56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cba688bf-6076-4613-85cc-3935034ecbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d4956c0-ec9c-4e4e-828d-7b85517a714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>0c6a3071-afc1-470c-aec6-cef4fae3b7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>dde8f627-15a3-4972-b9b0-164a1ca9b838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA</value>
      <webElementGuid>0199646f-6076-4e72-a885-8a9dc2c9ac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>9aa39348-3eb7-4593-a6c9-4645f75b2421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>f9df6070-3a81-4871-aadb-1c93f7ec27ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>b327f1d1-f3b0-4958-a7c8-3306c81072d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>f5b74f94-6879-4764-8165-0c1a3d4a4448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>68422ea0-08ea-4acc-a292-989e64b68b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>5e7b5758-1cbd-4e0a-8b14-0e87b565cc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>613bc847-aa7a-4c79-a6f5-a6047a33695d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>bead0359-d668-4c2d-9036-db36b54f5365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA' or . = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA')]</value>
      <webElementGuid>4b88c531-5d8f-4970-a058-38507e08acf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
