<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Desa  KelurahanGEDONGKIWOMANTRIJERON_b15df8 (1) (1)</name>
   <tag></tag>
   <elementGuidId>be1bf9df-9914-48b2-bc0d-1c51e825e9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Desa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Desa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba4d9626-bbbd-4ebe-89c8-7686283b6c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e215da3b-e523-4228-9636-040908fee22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Desa</value>
      <webElementGuid>29fd2a13-0e55-45ee-9b66-dbbd2c81bddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Desa_Kelurahan</value>
      <webElementGuid>42fa2817-109d-4e35-b225-d0609bd4e8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN</value>
      <webElementGuid>d2f73fff-550f-4128-b100-1fe69d673a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desa&quot;)</value>
      <webElementGuid>ab12fdec-2c13-4a36-a4fb-3dd06af94b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Desa']</value>
      <webElementGuid>2103d212-acd3-4576-bf54-860eb729ff6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[3]/select</value>
      <webElementGuid>0806a3e6-cd01-4dda-a8cb-f872aecded3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/following::select[1]</value>
      <webElementGuid>e1e5c526-8d0c-4c07-b0e8-c2e0d73d7729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[2]</value>
      <webElementGuid>7fcd8da8-163f-43b9-af5c-99d1e58cd274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[1]</value>
      <webElementGuid>5c3f539a-4b9d-4635-90c2-79ba0e0af66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/preceding::select[1]</value>
      <webElementGuid>2b98a915-ffc5-456f-85f3-7594c5ae0982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/select</value>
      <webElementGuid>9a0cdb50-aeb0-4f50-be93-4095fafc574e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Desa' and @name = 'Desa_Kelurahan' and (text() = 'Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN' or . = 'Desa / KelurahanGEDONGKIWOMANTRIJERONSURYODININGRATAN')]</value>
      <webElementGuid>7cd3104e-5c90-43cf-9e9e-a5d46df42c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
